title: <p align="center"> Alex Herrera Brietzke # your name (or website title) here

logo: "images/logo_alex_gh.png?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="pdf/CV_AlexHB_03_22.pdf" target="_blank" rel="noopener noreferrer">Resume</a> |
  <a href="https://www.linkedin.com/in/alex-herrera-brietzke-2ab09897/" target="_blank" rel="noopener noreferrer">LinkedIn</a> |
  <a href="https://alexela14.wixsite.com/alexherrera" target="_blank" rel="noopener noreferrer">Personal Site</a> 
  </p>
  
  <p align="center">
  B.A. Digital Marketing 
  
  
  <p align="justify">
  During my graduate studies my interest for data analysis and vizualisation has grown significaly. 
  <br><br>
  This portfolio serves as a showcase for the most important projects developed till the date.
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-5TGX4BX4V8 # your Google Analytics tracking ID here
