title: Alex Herrera Brietzke # your name (or website title) here
logo: "logo_alex_gh.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="CV_AlexHerreraB_10.21.pdf">Resume</a> 
  |
  <a href="https://www.linkedin.com/in/alex-herrera-brietzke-2ab09897/">LinkedIn</a> 
  |
  <a href="https://alexela14.wixsite.com/alexherrera">Personal Site</a> 
  <br><br>
  B.A. Digital Marketing 
  <br><br>
  Towards the end of my studies my interest for data analysis and vizualisation has been growing steadily. 
  This repository will serve as a showcase for the most important projects developed till the date.
  <br><br>

theme: jekyll-theme-minimal
google_analytics: G-HLC2MP254E # your Google Analytics tracking ID here
