title: <p align="center"> Alex Herrera Brietzke # your name (or website title) here

logo: "logo_alex_gh.png?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="CV_AlexHerreraB_11.21.pdf" target="_blank" rel="noopener noreferrer">Resume</a> |
  <a href="https://www.linkedin.com/in/alex-herrera-brietzke-2ab09897/" target="_blank" rel="noopener noreferrer">LinkedIn</a> |
  <a href="https://alexela14.wixsite.com/alexherrera" target="_blank" rel="noopener noreferrer">Personal Site</a> 
  </p>
  
  <p align="center">
  B.A. Digital Marketing 
  
  
  <p align="justify">
  Towards the end of my studies my interest for data analysis and vizualisation has been growing steadily. 
  <br><br>
  This repository will serve as a showcase for the most important projects developed till the date.
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-HLC2MP254E # your Google Analytics tracking ID here
